export default {
  // Navbar / autenticação
  termosdeuso: 'Termos de Uso',
  aceitotermosdeuso: 'Li e aceito os termos de uso',
  linguagem: 'Linguagem',
  portugues: 'Português',
  espanhol: 'Espanhol',
  ingles: 'Inglês',
  titletreinamentos: 'Treinamentos',
  sair: 'Sair',

  // Menu principal (sidebar)
  configuracao: 'Configuração',
  recrutamentoselecao: 'Recrutamento e Seleção',
  planodeacao: 'Plano de Ação',
  movimentacaoregistro: 'Movimentação e Registro',
  jornadatrabalho: 'Jornada de Trabalho',
  remuneracaobeneficios: 'Remuneração e Benefícios',
  integracaotreinamento: 'Integração e Treinamento',
  acompanhamentoretencao: 'Acompanhamento e Retenção',
  desenvolvimentoecarreira: 'Desenvolvimento e Carreira',
  analiseserelatorios: 'Análises e Relatórios',
  avaliacoeseinspecoes: 'Avaliações e Inspeções',
  saudeeseguranca: 'Saúde e Segurança',

  // Navigation / Tabs
  feed: 'Feed',
  prontuariodocolaborador: 'Prontuário do colaborador',
  dossiedocolaborador: 'Dossiê do colaborador',
  exibirdossiecolaborador: 'Exibir no dossiê do colaborador',
  conternodossie: 'Conter no dossiê',
  consultahierarquia: 'Consulta hierarquia',
  baseconhecimento: 'Base de conhecimento',
  solicitacoes: 'Solicitações',
  planodereversao: 'Plano de reversão',
  dossievirtual: 'Workplace',

  // Tabs inside dossier
  pessoais: 'Dados pessoais',
  funcionais: 'Dados funcionais',
  sociais: 'Dados sociais',
  historicomovimentacao: 'Histórico de movimentações',
  documentacao: 'Documentação',

  // Common
  salvar: 'Salvar',
  cancelar: 'Cancelar',
  avancar: 'Avançar',
  voltar: 'Voltar',
  filtrar: 'Filtrar',
  editar: 'Editar',
  excluir: 'Excluir',
  acoes: 'Ações',
  novo: 'Novo',
  sim: 'Sim',
  nao: 'Não',
  ok: 'Ok',
  opcional: 'opcional',
  obrigatorio: 'Obrigatório',
  camposobrigatorios: 'Campos obrigatórios',
  camposnaopreenchidos: 'Há campo(s) obrigatório(s) não preenchido(s)',
  cliqueparaselecionar: 'Clique para selecionar',
  selecione: 'Selecione',
  cadastre: 'Cadastre',
  um: 'um',
  uma: 'uma',
  em: 'em',
  a: 'a',
  o: 'o',
  do: 'do',
  da: 'da',
  outro: 'Outro',

  // Person fields
  nome: 'Nome',
  informenome: 'Informe o nome',
  documento: 'Documento',
  documentoidentificacao: 'Documento de identificação',
  textodocumentoidentificacao: 'Informe o documento',
  datanascimento: 'Data de nascimento',
  informedatanascimento: 'Informe a data de nascimento',
  celular: 'Celular',
  informetelefonecelular: 'Informe o telefone celular',
  nomepai: 'Nome do pai',
  informenomepai: 'Informe o nome do pai',
  nomemae: 'Nome da mãe',
  informenomemae: 'Informe o nome da mãe',
  email: 'E-mail',
  informeemail: 'Informe o e-mail',
  foto: 'Foto',
  arquivo: 'Arquivo',
  escolhaarquivo: 'Escolha um arquivo ou arraste-o...',
  concordareceberwhatsappdaempresa: 'Concordo em receber mensagens via WhatsApp da empresa',
  informepis: 'Informe o PIS',
  atualizada: 'atualizada com sucesso!!!',

  // Address fields
  pais: 'País',
  codigopostal: 'Código postal',
  informecodigopostal: 'Informe o código postal',
  logradouro: 'Logradouro',
  informelogradouro: 'Informe o logradouro',
  numero: 'Número',
  informenumero: 'Informe o número',
  bairro: 'Bairro',
  informebairro: 'Informe o bairro',
  cidade: 'Cidade',
  cidademin: 'cidade',
  informecidade: 'Informe a cidade',
  estado: 'Estado',
  estadomin: 'estado',
  informeestado: 'Informe o estado',

  // Admission fields
  dataadmissao: 'Data de admissão',
  informedataadmissao: 'Informe a data de admissão',
  datainicioprestacaoservicos: 'Data início prestação de serviços',
  informedatainicioprestacaoservicos: 'Informe a data de início',
  empresa: 'Empresa',
  empresamin: 'empresa',
  estrutura: 'Estrutura',
  estruturas: 'Estruturas',
  estruturamin: 'estrutura',
  cargo: 'Cargo',
  cargomin: 'cargo',
  funcao: 'Função',
  funcaomin: 'função',
  salario: 'Salário',
  informesalario: 'Informe o salário',
  jornadadetrabalho: 'Jornada de trabalho',
  jornadamin: 'jornada',
  jornadas: 'Jornadas',
  vinculo: 'Vínculo',
  vinculomin: 'vínculo',
  vinculos: 'Vínculos',
  motivoadmissao: 'Motivo de admissão',
  motivomin: 'motivo',
  cadastreummotivo: 'Cadastre um motivo de admissão',
  lideranca: 'Liderança',
  referencias: 'Referências',
  admissao: 'Admissão',

  // CNH fields
  cnh: 'CNH',
  tipodelicenca: 'Tipo de licença',
  validadelicencadeconducao: 'Validade da licença de condução',
  informevalidadelicencadeconducao: 'Informe a validade',
  validadepermissaodeconducaonobrasil: 'Validade permissão de condução no Brasil',
  informevalidadepermissaodeconducaonobrasil: 'Informe a validade',
  licencadeconducaoparaestrangeiros: 'Licença de condução para estrangeiros',
  datadevalidadedalicencadeconducaodocolaboradornoseupaisdeorigem: 'Data de validade da licença no país de origem',
  datalimitequeestecolaboradorpoderaconduzirnobrasilusandoapermissaodeconducaosemacnh: 'Data limite para conduzir no Brasil sem CNH',
  paisdenacionalidadedocondutor: 'País de naturalidade do condutor',

  // Status labels
  situacaoatualcolaborador: 'Situação atual do colaborador',
  statusativo: 'Ativo',
  statusafastado: 'Afastado',
  statusausente: 'Ausente',
  statusferias: 'Férias',
  statusdemitido: 'Demitido',
  status: 'Status',
  statusmin: 'status',

  // Movement history
  tipodemovimentacao: 'Tipo de movimentação',
  selecioneotipodemovimentacao: 'Selecione o tipo de movimentação',
  datamovimentacao: 'Data movimentação',
  datainicial: 'Data inicial',
  datafinal: 'Data final',
  informedataincial: 'Informe a data inicial',
  informedatafinal: 'Informe a data final',
  datacadastro: 'Data de cadastro',
  dataatualizacao: 'Data de atualização',
  dataexclusao: 'Data de exclusão',
  cadastradopor: 'Cadastrado por',
  atualizadopor: 'Atualizado por',
  excluidopor: 'Excluído por',
  dadosdocolaborador: 'Dados do colaborador',
  datafinalsuperiorinvalida: 'A data final não pode ser anterior à data inicial',
  templatededatacomhorario: 'DD/MM/YYYY HH:mm',

  // Reports / Export
  exportardadosresumidos: 'Exportar dados resumidos',
  exportardadoscompletos: 'Exportar dados completos',
  relatoriodedadosresumidos: 'Relatório de dados resumidos',
  relatoriodedadoscompletos: 'Relatório de dados completos',
  gerarrelatorio: 'Gerar relatório',
  erroaogerarrelatorio: 'Erro ao gerar relatório',

  // Knowledge base
  conteudos: 'Conteúdos',
  grade: 'Grade',

  // Requests
  responderformulario: 'Responder formulário',
  placeholderbuscanomeformulario: 'Buscar pelo nome do formulário...',
  limparpesquisa: 'Limpar pesquisa',
  identificacaodocolaborador: 'Identificação do colaborador',
  obrigadoparticipacao: 'Obrigado pela participação',
  respostaenviada: 'Sua resposta foi enviada',

  // Rollback plan
  followdoplanodereversao: 'Follow do plano de reversão',
  placeholderbuscaplanoreversao: 'Buscar pelo nome do plano...',
  naoexisteumprativovinculadoaoseuusuario: 'Não existe um PR ativo vinculado ao seu usuário',
  nenhumresultadoencontrado: 'Nenhum resultado encontrado',

  // Errors / Validation
  erroaosalvarregistro: 'Erro ao salvar registro',
  erroaoexcluirregistro: 'Erro ao excluir registro',
  datanascimentomaioratual: 'A data de nascimento não pode ser maior que a data atual',
  dataanoinvalido: 'O ano informado é inválido',
  dataadmissaoinvalida: 'A data de admissão não pode ser maior que a data atual',
  informeCPFvalido: 'Informe um CPF válido',
  existepessoavinculadaaodocumento: 'Já existe uma pessoa vinculada ao documento informado',

  // Duplicates
  duplicateContactAlert: 'Existem informações de contato duplicadas. Resolva os conflitos antes de prosseguir.',
  duplicated_email: 'Este e-mail já está em uso por outro colaborador',
  duplicated_phone: 'Este celular já está em uso por outro colaborador',
  viewDuplicates: 'Ver duplicados',

  // Collaborator search
  colaborador: 'Colaborador',
  atualizardadoscadastrais: 'Atualizar dados cadastrais',
  datademissao: 'Data de demissão',

  // Registration data
  voltarparaoprontuario: 'Voltar para o prontuário',
  atualizacaodedadossociaisconcluida: 'Atualização de dados sociais concluída',
  conteudomodalsalvardadoscadastrais1: 'Os dados da aba',
  conteudomodalsalvardadoscadastrais2: 'foram atualizados com sucesso!',
  seuusuarionaopossuiprivilegioparaeditarestecampo: 'Seu usuário não possui privilégio para editar este campo',

  // Other
  atualizar: 'Atualizar',
  usuario: 'Usuário',
  usuarionaocolaborador: 'Usuário não é colaborador',
  usuarionaoidentificado: 'Usuário não identificado',
  semplanejamentosativos: 'Sem planejamentos ativos',
  formularionaoencontrado: 'Formulário não encontrado',
  formrespondidomaisdeumavezmesmapessoa: 'Este formulário já foi respondido por este usuário',
  vagaaqualserefere: 'Vaga a qual se refere',
  vaga: 'vaga',
  unidadenaovinculadaaempresa: 'Esta unidade não está vinculada à empresa selecionada',
  umoumais: 'um ou mais',
  pessoais_short: 'Pessoais',
  descricao: 'Descrição',
  tipo: 'Tipo',
  visualizar: 'Visualizar',
  veragendamentos: 'Ver agendamentos',
  agendamento: 'Agendamento',
  dataderealizacao: 'Data de realização',
  datainicio: 'Data de início',
  datatermino: 'Data de término',
  na: 'N/A',
  presente: 'Presente',
  remanejado: 'Remanejado',
  faltou: 'Faltou',
  atrasado: 'Atrasado',
  colaboradorconcluiuagendamento: 'O colaborador concluiu o agendamento.',
  colaboradordispensadopenaliza: 'Colaborador dispensado, não penaliza aderência.',
  agendamentodisponivelparainicioimediato: 'Agendamento disponível para início imediato.',
  agendamentodisponivelporemforadoprazo: 'Agendamento disponível, porém fora do prazo.',
  agendamentoindisponivelaguardeadatadeinicio: 'Agendamento indisponível, aguarde a data de início.',
  adatadeterminodesteagendamentojapassou: 'A data de término deste agendamento já passou.',
  esteagendamentonaoestamaisdisponivel: 'Este agendamento não está mais disponível.',
  treinamentos: 'Treinamentos',
  novotreinamento: 'Novo treinamento',
  placeholderbuscanomeoudescricaotreinamento:
    'Buscar pelo nome ou objetivo do treinamento',
  placeholderbuscanometreinamento: 'Buscar pelo nome do treinamento',
  formularios: 'Formulários',
  avaliacoes: 'Avaliações',
  gradetreinamentos: 'Grade de treinamentos',
  cadastros: 'Cadastros',
  dadosmockadosformularios:
    'Lista mockada de formulários (substitui o fluxo completo com API/DMForm).',
  dadosmockadosavaliacoes:
    'Lista mockada de avaliações (substitui o fluxo completo com API/DMEvaluation).',
  respostas: 'Respostas',
  ver: 'Ver',
  treinamento: 'Treinamento',
  origem: 'Origem',
  statusdotreinamento: 'Status do treinamento',
  periodo: 'Período',
  limparfiltros: 'Limpar filtros',
  nomedotreinamento: 'Nome do treinamento',
  progresso: 'Progresso',
  prazo: 'Prazo',
  conclusao: 'Conclusão',
  agendado: 'Agendado',
  emandamento: 'Em andamento',
  concluido: 'Concluído',
  exportardadosparaexcel: 'Exportar dados para Excel',
  exportarparaexcel: 'Exportar para Excel',
  rascunho: 'Rascunho',
  pendente: 'Pendente',
  prorrogado: 'Prorrogado',
  ultimos30dias: 'Últimos 30 dias',
  ultimos60dias: 'Últimos 60 dias',
  ultimos90dias: 'Últimos 90 dias',
  ultimoano: 'Último ano',
  datapersonalizada: 'Data personalizada',
  de: 'De',
  ate: 'Até',

  // Cadastro de treinamento (TrainingRegister / DMPeople)
  cadastro: 'Cadastro',
  planejamento: 'Planejamento',
  quantidademaximadeagendamentosinfo: 'Quantidade máxima de agendamentos:',
  diasaposplanejamentoalerttitulo: 'Dias após o início da prestação de serviços',
  diasaposplanejamentoalerttexto:
    'Novos agendamentos são permitidos enquanto houver unidades pendentes de planejamento. Quando não restar nenhuma, não será possível cadastrar mais.',
  diasapospillpodecadastrar:
    'Cadastre agendamentos enquanto houver unidades pendentes ({pendentes}).',
  diasapospillcadastradoscomresto:
    '{count} agendamento(s) cadastrado(s). Restam {pendentes} unidade(s) pendente(s).',
  diasapospillsempendentes:
    'Não há unidades pendentes — não é possível cadastrar novos agendamentos.',
  vocepodecriaratéagendamentosparatreinamento:
    'Você pode criar até {count} agendamentos para este treinamento',
  unidadespendentesplanejamentohelper:
    '{pendentes} de {total} unidades pendentes de planejamento',
  unidadespendentesplanejamentosecao: 'Unidades pendentes de planejamento:',
  selecioneaunidade: 'Selecione a unidade',
  nenhumagendamentocadastradopodeate:
    'Nenhum agendamento cadastrado, você pode cadastrar até {max}',
  agendamentoscadastradoscontagem:
    '{current} de {max} agendamentos cadastrados neste treinamento',
  nenhumagendamentocadastradoainda: 'Nenhum agendamento cadastrado ainda.',
  selecioneunidadepreenchadadosprimeiro:
    'Selecione uma unidade e preencha os dados para criar o primeiro agendamento.',
  todososagendamentosplanejados:
    'Todos os agendamentos deste treinamento já foram planejados.',
  umagendamentocadastradopodemais:
    '1 agendamento cadastrado, você ainda pode cadastrar mais {rest}',
  nagendamentoscadastradospodemais:
    '{count} agendamentos cadastrados, você ainda pode cadastrar mais {rest}',
  unidadeslabelresumo: 'Unidade(s):',
  dataprevistadeiniciolabel: 'Data prevista de início:',
  dataterminolabel: 'Data de término:',
  tempodeduracaolabel: 'Tempo de duração:',
  instrutorlabel: 'Instrutor:',
  instrutornaoinformado: '-',
  pessoasparticipanteslabel: 'Pessoas participantes:',
  checkderetencaolabel: 'Check de retenção:',
  avaliacaodereacaolabel: 'Avaliação de reação:',
  certezaexcluiragendamento: 'Excluir este agendamento? Os dados preenchidos serão perdidos.',
  atencao: 'Atenção',
  quaispessoasparticiparao: 'Quais pessoas participarão?',
  selecioneaspessoas: 'Selecione as pessoas',
  digiteotempoemminutos: 'Digite o tempo em minutos',
  selecioneoformulario: 'Selecione o formulário',
  pessoasselecionadasresumo: '{count} pessoa(s) selecionada(s)',
  digiteonomedoinstrutor: 'Digite o nome do instrutor',
  dataprevistadeinicio: 'Data prevista de início',
  datadetermino: 'Data de término',
  tempodeduracaodoagendamentoemminutos:
    'Tempo de duração do agendamento (em min.):',
  checkderetencao: 'Check de retenção',
  avaliacaodereacao: 'Avaliação de reação',
  indicarinstrutor: 'Indicar instrutor',
  informeotempodeduracaoemmin: 'Informe o tempo de duração em min.',
  cliqueparaselecionarumaavaliacao: 'Clique para selecionar uma avaliação',
  cliqueparaselecionarumformulario: 'Clique para selecionar um formulário',
  errocarregarelegiveis: 'Erro ao carregar colaboradores elegíveis.',
  estecolaboradornaopodeserremovido:
    'Este colaborador não pode ser removido.',
  nometreinamento: 'Nome do treinamento',
  nenhumaopcaodisponivel: 'Nenhuma opção disponível',
  semsubopcoes: 'Sem sub-opções',
  vocedeveselecionaronivelnoqualotreinamentoseraalocado:
    'Você deve selecionar o nível no qual o treinamento será alocado.',
  indicadorassociado: 'Indicador associado',
  quaiskpismetricassaoimpactadospelarealizacaodestetreinamento:
    'Quais KPIs/métricas são impactadas pela realização deste treinamento.',
  descreveroindicador: 'Descrever o indicador',
  valordotreinamento: 'Valor do treinamento',
  valormonetariorecursofinanceiroqueseraaplicadonestetreinamento:
    'Valor monetário, recurso financeiro que será aplicado neste treinamento.',
  anoreferencia: 'Ano referência',
  selecioneoanoreferencia: 'Selecione o ano de referência',
  otreinamentoeobrigatorio: 'O treinamento é obrigatório?',
  planejamentorecorrente: 'Planejamento recorrente',
  marqueessaopcaoparatreinamentosqueacontecemdeformacontinua:
    'Marque essa opção para treinamentos que acontecem de forma contínua.',
  umaoumais: 'uma ou mais',
  gradesmin: 'grades',
  estruturasmin: 'estruturas',
  agendamentos: 'Agendamentos',
  tipoagendamento: 'Tipo de agendamento',
  selecioneumtipodeagendamento: 'Selecione um tipo de agendamento',
  quantidadedeagendamentos: 'Quantidade de agendamentos',
  selecioneaquantidadedeagendamentos: 'Selecione a quantidade de agendamentos',
  diasaposiniciodaprestacaodeservicos:
    'Dias após início da prestação de serviços',
  insiraaquantidadededias: 'Insira a quantidade de dias',
  tipodevinculo: 'Tipo de vínculo',
  selecioneumoumaistiposdevinculo: 'Selecione um ou mais tipos de vínculo',
  tiposcargos: 'Tipos de cargos',
  tiposcargosmin: 'tipos de cargos',
  quaiscargosdevemparticipar: 'Quais cargos devem participar?',
  cargosmin: 'cargos',
  quaisfuncoesparticiparaodotreinamento:
    'Quais funções participarão do treinamento',
  funcoesmin: 'funções',
  quaiscolaboradoresparticiparaodotreinamento:
    'Quais colaboradores participarão do treinamento?',
  colaboradoresmin: 'colaboradores',
  admitidosapartirde: 'Admitidos a partir de',
  objetivodotreinamento: 'Objetivo do treinamento',
  descrevaoobjetivodotreinamento: 'Descreva o objetivo do treinamento',
  contabilizarnomodulodeperformance: 'Contabilizar no módulo de performance',
  indicadorcorrespondentenomodulodeperformance:
    'Indicador correspondente no módulo de performance',
  selecioneoindicador: 'Selecione o indicador',
  palavraschaverelacionadasaotreinamento:
    'Palavras-chave relacionadas ao treinamento',
  selecioneocertificado: 'Selecione o certificado',
  templatecertificado: 'Template do certificado',
  somenteimagempng: 'somente imagem PNG',
  informepalavrachave: 'Informe uma palavra-chave',
  ocamponaopodetermaisque500caracteres:
    'O campo nome do treinamento não pode ultrapassar 500 caracteres',
  pressioneenterparaselecionar: 'Pressione enter para selecionar',
  presioneenterpararemover: 'Pressione enter para remover',
  selecionado: 'Selecionado',
  marcartodos: 'Marcar todos',
  semregistros: 'Sem registros',
  nenhumcolaboradorencontrado: 'Nenhum colaborador encontrado',
  vinculadoaumcolaboradordeoutraunidade:
    'Há colaborador vinculado de outra unidade a este vínculo/cargo/função.',
  textonomecampo: 'Texto de ajuda do campo',
  atualizado: 'atualizado',
  cadastrado: 'cadastrado',
  naoepossivelatualizarpoisotreinamentojainiciou:
    'Não é possível atualizar pois o treinamento já iniciou.',
  naoepossivelsalvarpoisjaexisteumtreinamentocomestenome:
    'Não é possível salvar pois já existe um treinamento com este nome.',
  cliqueparaselecionarouarrasteoarquivo:
    'Clique para selecionar ou arraste o arquivo',
  unidadeinativa: 'unidade inativa'
}
